
services:
  db:
    image: postgres:latest
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend_api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://user:password@db/todo_db

  frontend:
    build: ./frontend
    container_name: frontend_ui
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - BROWSER=none 
      - CACHE_LOCATION=/tmp/.eslintcache

volumes:
  postgres_data:

